# arch-java
#
# base/arch with jre7-openjdk-headless
FROM base/arch
MAINTAINER totokaka <mail@totokaka.io>

# Update the installation
RUN pacman -Syu --noconfirm

# Install headless Java JRE
RUN pacman -S --noconfirm jre7-openjdk-headless
